name: gseim-ci
on: [push, pull_request]
jobs:
  build-and-test:
    strategy:
      matrix:
        python-version: ['3.8'] # , '3.9']
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./gseim_grc/src/
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Ubuntu and Python package dependencies
        run: |
          sudo apt install libgirepository1.0-dev libcairo2-dev pkg-config gir1.2-gtk-3.0 qtbase5-dev libxkbcommon-x11-0
          pip3 install pyqt5
      - name: Run Bazel test
        run: |
          mkdir ~/.cache/gseim/
          chmod 777 ~/.cache/gseim/
          bazel test //...
      - name: Build Linux wheel
        run: |
          bazel build //:gseim_wheel
          # This is required due to https://github.com/actions/upload-artifact/issues/92.
          cp bazel-bin/gseim-*.whl /home/runner/work/gseim/gseim
      - name: Try installing wheel
        run: |
          pip3 install gseim-*.whl
          `python3 -c "import gseim_cpp_lib; from importlib_resources import files; str(print(files('gseim_cpp_lib').joinpath('gseim_solver')))"` ./gseim_grc/src/gseim_cpp_lib/test_data/input/ac_controller_1.in ./gseim_grc/src/gseim/data
        working-directory: /home/runner/work/gseim/gseim
      - name: Audit wheel
        run:
          pip3 install auditwheel
          auditwheel bazel-bin/gseim-*.whl
      - name: Upload Linux wheel
        uses: actions/upload-artifact@v3
        with:
          name: gseim-wheel
          path: gseim-*.whl
